version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10.0
    filters:
      branches:
        ignore: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: lint
          command: npm run lint
  deploy:
    docker:
    - image: circleci/node:10.10.0
    steps:
    - checkout
    - restore_cache:
        keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: npm ci
    - save_cache:
        paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
        key: node-v1-{{ checksum "package-lock.json" }}
    - run:
        name: Deploy Master to GitHub
        command: |
            git config --global user.email "yaoandy107@gmail.com"
            git config --global user.name "yaoandy107"
            ./deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
